### ISSUE TITLE
Amstrad CPC Instructions are incorrect.

### ISSUE THREAD

**Issue by muckypaws** [spotlessmind1975/pick-the-star-10liner#1]
Hello,

The instructions provided to run the CPC version are incorrect.  This is what is needed :- 

MODE 1:MEMORY &11FF:LOAD"MAIN.COM",&1200:CALL &1200

Without the Mode command ugBasic doesn't correctly reset the screen offset if the screen has scrolled.

It would be better to add the correct startup sequence as an additional file on disk to help the end user playing the game.

Additionally, if you're not using CP/M the game code should be .BIN and not .COM

Hope this helps.

**Comment by spotlessmind1975** [comment]
Hello @muckypaws , first of all **thank you for your bug report and suggestions**!

I opened a series of issues directly on the [ugBASIC project](https://ugbasic.iwashere.eu/), so that all the next executables, and not only this one, will take advantage of your excellent advice and suggestions. 

In particular:
  * [Update loading instructions (cpc) cpc](https://github.com/spotlessmind1975/ugbasic/issues/584)
  * [Change output file name to bin (cpc)](https://github.com/spotlessmind1975/ugbasic/issues/583)
  * [Add startup sequence on disk image](https://github.com/spotlessmind1975/ugbasic/issues/582)
  * [Fix startup sequence if scrolled (cpc)](https://github.com/spotlessmind1975/ugbasic/issues/581)

I will correct also this game, and I will update this issue, as well.

Thank you again!

**Comment by muckypaws** [comment]
Hello, 

Thank you for a quick response, which was unexpected. 

If you’re in the mood for raising cases with the creator of ugBasic, may I suggest that rather than the requirement for a “Loader” or adjusting the instructions.  To simply change the header of the executable file to load at the correct memory address and execute at that address too, that way you avoid all the additional faff and have a development that runs unhindered.

SOFT968 - Amstrad CPC Firmware Guide Section 9.3 describes the file header structure, though if ugBASIC is writing the file directly to Amstrad it should set the correct data with the SAVE calls to #BC98 when writing the file. 

Hope this helps.

And Kind Regards

**Comment by spotlessmind1975** [comment]
hello @muckypaws, and **thank you again for the comment!**

The suggestion is welcome, indeed it is really interesting. I need to see how to introduce this change: maybe I can add an option to differentiate a headerless binary from a header one. I want to carefully investigate the documentation you suggest, because it might become the best solution. In the meantime, I've started by updating the instructions, because if they're wrong, they have to be corrected, to avoid creating problems (also in the [UGBASIC-IDE](https://spotlessmind1975.itch.io/ugbasic-ide), that "autotypes" the same command).

__Thank you very much again!__

ps. probably the creator of ugBASIC will be sympathetic to my comments, since... that's me. ;-)

**Comment by muckypaws** [comment]
Oh wow, you’re the creator of ugBasic? Nicely done!

In that case, I used to be a hacker back in the 80s for the AmstradCPC, I can definitely share pointers with you.

Good luck with your project.

Incidentally I write articles and interviews for the Blast Annual https://blastannual.com, this is an interesting project we’d like to cover in a future edition.  If you’re interested, either DM me in GitHub or message me here: https://muckypaws.com/about/ to exchange email addresses.

Kind Regards

**Comment by spotlessmind1975** [comment]
Hello @muckypaws, first of all thank you very much, you are very kind! I'm flattered that you like the ugBASIC project. Above all, I'm happy to be able to get in touch with those who have had direct experience with this computer, and that could give me useful advice to improve the project!

Going back to the suggestion you kindly provided, I did some digging with the resources you gave me and I made the series of changes you suggested. In addition to omitting the executable suffix, it now correctly indicates both the load address and the start address in the header. So now the game can be loaded with the statement:

     RUN"MAIN

I've recompiled the game, and updated the instructions accordingly. 

Of course, the previous instructions will work too (including `MODE 1`) but, from what I understood by the technical reference, with the `RUN` command of LocomotiveBASIC calls the kernel routine which also resets the screen offset, in case the screen has scrolled. On this last point, however, I'd like to have any confirmation, if as an operation it can be sufficient or if you think it is necessary to intervene on the Gate Array initialization routine.

Than you again, and kind regards
